version: '3'
services:
  app:
    restart: always
    build: .
    network_mode: host
#    ports:
#      - $APP_PORT:$APP_PORT
    command: $DOCKER_APP_RUN_CMD
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:12.5-alpine
    restart: always
#    network_mode: bridge
    volumes:
      - dbvolume:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
    ports:
      - $POSTGRES_PORT:$POSTGRES_PORT
    command: -p $POSTGRES_PORT

volumes:
  dbvolume: