version: '3'
services:
  app:
    restart: always
    build: .
    ports:
      - "8000:8000"
#    volumes:
#      - ./web:/app/web
    command: make run
#    environment:
#      FLASK_APP: project/__init__.py
    depends_on:
      - db
    working_dir: /app/web

  db:
    image: postgres:9.6-alpine
    restart: always
    volumes:
      - dbvolume:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app

volumes:
  dbvolume: