"""init

Revision ID: d2465f0cbdf4
Revises: 
Create Date: 2020-11-26 20:45:05.754932

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd2465f0cbdf4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('company_id_index', 'company', ['id'], unique=False, postgresql_using='hash')
    op.create_table('project',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('project_id_index', 'project', ['id'], unique=False, postgresql_using='hash')
    op.create_table('user',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('role', sa.Enum('owner', 'employee', name='globalroleenum'), nullable=False),
    sa.Column('company_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(('company_id',), ['company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('user_id_index', 'user', ['id'], unique=False, postgresql_using='hash')
    op.create_table('membership',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('project_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('role', sa.Enum('admin', 'manager', name='projectroleenum'), nullable=False),
    sa.ForeignKeyConstraint(('project_id',), ['project.id'], ),
    sa.ForeignKeyConstraint(('user_id',), ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('membership_id_index', 'membership', ['id'], unique=False, postgresql_using='hash')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('membership_id_index', table_name='membership')
    op.drop_table('membership')
    op.drop_index('user_id_index', table_name='user')
    op.drop_table('user')
    op.drop_index('project_id_index', table_name='project')
    op.drop_table('project')
    op.drop_index('company_id_index', table_name='company')
    op.drop_table('company')
    # ### end Alembic commands ###
